### ISSUE TITLE
Software installer: Error while Nextcloud installation

### ISSUE THREAD

**Issue by Hafii** [MichaIng/DietPi#3378]
───────┤ DietPi-Software | Error handler├───────

 - Command: ncc maintenance:install
 - Exit code: 1
 - DietPi version: v6.28.0 (MichaIng/master) | HW_MODEL:3 | HW_ARCH:2 | DISTRO:5
 - Image creator: DietPi Core Team
 - Pre-image: Raspbian Lite

Log file content:
Error while trying to create admin user: Failed to connect to the database: An
exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user
'tmp_root'@'localhost'
 ->

**Comment by MichaIng** [comment]
@Hafii 
Many thanks for your report. I'll check and provide some manual steps later.

**Comment by MichaIng** [comment]
Okay try to go though these steps manually:
```
systemctl start mariadb
systemctl start redis-server
ncc(){ sudo -u www-data php /var/www/nextcloud/occ "$@"; }
mysql -e "grant all privileges on *.* to 'tmp_root'@'localhost' identified by 'dietpi' with grant option"
ncc maintenance:install --no-interaction --database 'mysql' --database-name 'nextcloud' --database-user 'tmp_root' --database-pass 'dietpi' --admin-user 'admin' --admin-pass 'dietpi' --data-dir '/mnt/dietpi_userdata/nextcloud_data'
mysql -e 'drop user tmp_root@localhost'
```
- You can adjust `--admin-user` and `--admin-pass` values to your needs of course, which is the initial admin account to log into Nextcloud web UI.

If the above steps report success, **please do not log into Nextcloud yet**, but redo/finish the install first:
```
dietpi-software install 114
```

**Comment by Hafii** [comment]
Thank you for the quick response.
Still the same Error(with changed Admin Name) when executing: nn maintainance:install .....
Here the Error message:
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'oc_admin'@'localhost'

**Comment by MichaIng** [comment]
@Hafii 
Ah, it might be this: https://github.com/nextcloud/server/issues/18513
Strange only that it should have been fixed. We worked around the issue by pulling an older Nextcloud version, but all has been backported now: https://github.com/nextcloud/server/pull/19303
I'll try to replicate.

**Comment by MichaIng** [comment]
Install works pretty fine on my testing system, DietPi v6.28 pulls the specific NC17.0.1 which does not contain the bug.
```
[  OK  ] DietPi-Software | systemctl restart mariadb
[  OK  ] DietPi-Software | systemctl restart redis-server
[  OK  ] DietPi-Software | ncc maintenance:install
[  OK  ] DietPi-Software | Desired setting in /var/www/nextcloud/config/config.php was already set:   'mysql.utf8mb4' => true,
[  OK  ] DietPi-Software | Added setting 'memcache.local' => '\\OC\\Memcache\\APCu', to /var/www/nextcloud/config/config.php after line   'version' => '17.0.1.1',
[ INFO ] DietPi-Software | Enabling Redis for transactional file locking.
[  OK  ] DietPi-Software | Comment in /etc/redis/redis.conf converted to setting: unixsocket /run/redis/redis-server.sock
[  OK  ] DietPi-Software | Comment in /etc/redis/redis.conf converted to setting: unixsocketperm 777
[  OK  ] DietPi-Software | systemctl restart redis-server
```
So you issue must be different. Which webserver do you use? And do you see any other error logs during dietpi-software output?

I removed the workaround regardless, since it is not required anymore. But has been fixed with current NC18: https://github.com/MichaIng/DietPi/commit/8ab410ff29c359d22c86e600d5caaa9cc782c3f4#diff-d92a6ee04e02fd2a2dc23d5bec3e6a98L3448-R3448

**Comment by Hafii** [comment]
I am using a new DietPi installation, first and only thing i want to do is install nextcloud with the software installer. First time i got this issue was Christmas holidays(don't know which dietpi version is was, maybe v6.26...) now i updates DietPi and still get this error.

**Comment by MichaIng** [comment]
@Hafii 
This error happened once indeed because of the mentioned regression with NC17.0.2.

Did you flash the new DietPi image freshly or just retried installing Nextcloud on the same image? Probably there are issues because of the partial install done until failure.

Please try the following to purge all related installed software and start from scratch:
```
apt purge mysql-server lighttpd redis-server
apt autoremove --purge
rm -Rf /etc/{mysql,apache2} /mnt/dietpi_userdata/{mysql,nextcloud_data}
```
Then freshly install Nextcloud:
```
dietpi-software install 114
```

**Comment by CLUB777ONE** [comment]
dietpi-software install 114 - It does not work because the file "nextcloud-17.0.1.tar.bz2" is not available on the Nextcloud server.

Current DietPi uses this link to download nextcloud: https://download.nextcloud.com/server/releases/nextcloud-17.0.1.tar.bz2

Meanwhile, the Nextcloud v. 18.0.1 has been released. Is there a way to update the link in DietPi myself? If so, in which DietPi-File could I replace the old link with the new one?

https://download.nextcloud.com/server/releases/nextcloud-18.0.1.zip

**Comment by MichaIng** [comment]
Okay, basically the workaround has been removed and newest Nextcloud 18 has the issue solved, hence there should be no issue anymore with DietPi v6.29.

On our current testing images, I applied the fix as well and it is hacked into running systems via MOTD (a practice which I aim to replace with a transparent live-patches system).
