### ISSUE TITLE
Home Assistant - Python 3.13 

### ISSUE THREAD

**Issue by whyisthisbroken** [MichaIng/DietPi#7293]
In the next release of HA with Version 2024.12, Python is raised to version 3.13.

https://rc.home-assistant.io/blog/2024/11/26/release-202412#weve-upgraded-to-python-313

It might lead to certain problems and wanted to let you know in advance.

**Comment by yuukiAme** [comment]
No wonder my fresh install of Home Assistant kept being stuck at this stage

```
Downloading Python-3.12.7.tar.gz...
-> https://www.python.org/ftp/python/3.12.7/Python-3.12.7.tgz
Installing Python-3.12.7...
```

**Comment by Joulinar** [comment]
I doubt that there is a connection. It is to be expected that it will take a while at this stage. Depending on the SBC, it can even take a very long time.

**Comment by MichaIng** [comment]
Thanks for the heads up!

But it will still support Python 3.12: https://github.com/home-assistant/core/blob/dev/pyproject.toml

The news is only for the HA containers and appliances. It means at least that most relevant integrations do support Python 3.13 now. We will then also switch, once it is has been released. But no urgency.

**Comment by Dynamic5912** [comment]
Got this today after upgrading HA

![image](https://github.com/user-attachments/assets/a67cd0c6-d295-4ca3-a2d1-f1be862d7e4f)

**Comment by lukaszsobala** [comment]
@MichaIng I think it's more of an urgent issue...

I was having this error after updating to hass 2024.12: https://github.com/home-assistant/core/issues/131997
Tried a few things in pyenv like updating u but nothing worked. Only upgrading to python 3.13 helped. I did this by modifying the python version in dietpi-software to 3.13.0 and issuing `dietpi-software reinstall 157`. Now there are no errors.

**Comment by Dynamic5912** [comment]
Mine is working but I got the "warning" message I posted above.

They're not deprecating old Python until Feb 2025 for HA Core

**Comment by MichaIng** [comment]
@lukaszsobala 
The issue you linked is an error with the new HA version and Python 3.13, while someone solved it while still using Python 3.12. I guess the reinstall solved it for you, since it reinstalls all dependencies from scratch, including possibly needed updates.

> To be fair, I did not try reinstalling without this mod, so maybe 3.12.7 would still work...

I guess so. But I'll keep it in mind, in case someone else reports it.

Ah, and, since 2024.12 is released now, I'll update ours to Python 3.13 now anyway.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/de0af4b

**Comment by MichaIng** [comment]
@vdvdnk 
But HA starts up and is usable, right? I need to check the exact errors, but since we do not install FFmpeg with HA OOTB, logically all Python modules which try to load it fail. However, HA core does not require FFmpeg, but only video/audio/camera integrations do. Don't ask me why HA core adds heavy Python modules as dependencies which are needed only for a minority of users. I complained about this since years, but it keeps growing like this.

**Comment by vdvdnk** [comment]
Thanks, yes it starts up and usable

**Comment by MichaIng** [comment]
If anything does not work, like mentioned audio/video/camera integrations which require decoding or encoding on the HA host system, then:
```sh
apt install ffmpeg
```
That should also mute the error. But the set of libraries is huge, which is why we do not install it OOTB.

**Comment by vdvdnk** [comment]
Note that I also installed ffmpeg and libavcodec, error still persist. In previous version of HA 2024.11 no such errors (at least I haven't noticed that)

**Comment by MichaIng** [comment]
Ah hmm, then it is probably an issue with the FFmpeg version. ... indeed `AV_CODEC_FLAG_FRAME_DURATION` is declared in FFmpeg 6 but not in FFmpeg 5. But Debian Bookworm ships FFmpeg 5 only:
- https://ffmpeg.org/doxygen/6.0/avcodec_8h.html
- https://ffmpeg.org/doxygen/5.0/avcodec_8h.html
- https://packages.debian.org/ffmpeg

The `av` module uses it since v13.1:
- https://github.com/PyAV-Org/PyAV/blob/v13.1.0/av/codec/context.pyx
- https://github.com/PyAV-Org/PyAV/blob/v13.0.0/av/codec/context.pyx
- https://github.com/PyAV-Org/PyAV/pull/1533

Not sure whether they were aware it is a breaking change, but IIRC FFmpeg 6 was actually declared as dependency already.

Home Assistant declares v13.1 as minimum dependency version:
- https://github.com/home-assistant/core/blob/2024.12.1/requirements_all.txt#L535-L537

In v2023.11 it was still their own fork `ha-av`, which obviously did not contain this change yet:
- https://github.com/home-assistant/core/blob/2024.11.3/requirements_all.txt#L1067-L1069

Newer FFmpeg is available through this repository:
- https://www.deb-multimedia.org/dists/bookworm/main/binary-amd64/package/ffmpeg

**Comment by vdvdnk** [comment]
Thanks for the investigation! With FFmpeg from deb-multimedia.org av compiled successfully and HA works without any issues.

**Comment by MichaIng** [comment]
It is sadly difficult to implement this by default into DietPi FFmpeg installations. It contains a lot of other software and libraries, which can be incompatible with other Debian packages which depend on them, including own media packages we provide for each Debian version. And on RPi, the Kodi build from the RPi repo is needed to provide full hardware acceleration, while the one from the multimedia.org repo has a higher epoch version, hence will forcefully be installed ... and the one from RPi repo is likely not compatible with the shared libs from that repo etc etc 😄.

The switch (back) from `ha-av` to `av` was done here: https://github.com/home-assistant/core/pull/129699
A needed feature was added in v12.1.0 already, hence as a workaround, we could change the version dependency to `13.0.0`.

**Comment by Dynamic5912** [comment]
Some errors for me today:

![image](https://github.com/user-attachments/assets/0bfa99c1-0f6c-4368-bcad-bb2bbe6092ed)

![image](https://github.com/user-attachments/assets/cda7106d-28b4-4494-b1c3-ead1c79e0ce4)

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/homeassistant/components/stream/__init__.py", line 226, in async_setup
    await hass.async_add_executor_job(set_pyav_logging, debug_enabled)
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/homeassistant/components/stream/__init__.py", line 196, in set_pyav_logging
    import av  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/av/__init__.py", line 17, in <module>
    from av.bitstream import BitStreamFilterContext, bitstream_filters_available
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/av/bitstream/__init__.py", line 1, in <module>
    from .context import BitStreamFilterContext
  File "av/bitstream/context.pyx", line 1, in init av.bitstream.context
ValueError: av.frame.Frame size changed, may indicate binary incompatibility. Expected 56 from C header, got 48 from PyObject

![image](https://github.com/user-attachments/assets/8eec430e-6924-415e-89ba-ef0a47f190e4)

**Comment by lukaszsobala** [comment]
Solution seems to be here https://github.com/home-assistant/core/issues/131997#issuecomment-2543853747

**Comment by MichaIng** [comment]
So it is two dedicated issues: one as of left over files from `ha-av` when migrating to `av`, causing @Dynamic5912's error, and is solved by explicitly uninstalling the `ha-av` module, before the migration, or uninstalling `av` once to cleanup, then let HA pull is freshly.

The other one is due to `av` 13.1.0 requiring FFmpeg 6, which is not available on Debian Bookworm natively. It does not crash anything, but video and camera integrations might not work or run into actual GUI/usage failures. In this case, adding https://www.deb-multimedia.org/ is a workaround, of upgrading to Debian Trixie, which ships FFmpeg 7.

I'll test whether manually pinning down the `av` version to 13.0.0 works.

**Comment by Dynamic5912** [comment]
Do I need to do anything or await further instructions/next DietPi release?

**Comment by MichaIng** [comment]
Next DietPi release will ship HA with Python 3. But it most likely won't have the FFmpeg issue worked around yet.

**Comment by whyisthisbroken** [comment]
So, compiled ffmpeg by myself and install it, removed the old one from the deb rep and do the fix from here https://github.com/home-assistant/core/issues/131997#issuecomment-2543853747

Everything works find - now waiting for the python 3.13 fix with the next dietpi release and all done :)

**Comment by Dynamic5912** [comment]
Was this fixed in 9.9?

Any additional steps to take?

**Comment by whyisthisbroken** [comment]
Good question - i dont see anything about that in the changelog... so i dont updatet yet...

**Comment by Joulinar** [comment]
Its on master branch as you can see

https://github.com/MichaIng/DietPi/blob/c9eda88a02d0836ba9c6c538874ea85274087dc2/dietpi/dietpi-software#L11381

**Comment by whyisthisbroken** [comment]
So, i´ve updatet to 9.9 and reinstalled HA.
After that the warning comes up:
```
Logger: aiohttp_fast_zlib
Quelle: components/http/__init__.py:204
Erstmals aufgetreten: 09:43:36 (1 Vorkommnisse)
Zuletzt protokolliert: 09:43:36

zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
```

So i installed this `pip install zlib_ng isal` in the HA pyenv and restart HA - Warning gone....

Thanks for fixing - and merry christmas :)

**Comment by Dynamic5912** [comment]
So I need to reinstall HA?

**Comment by whyisthisbroken** [comment]
Yes

**Comment by Joulinar** [comment]
> So I need to reinstall HA?

as usual

**Comment by Dynamic5912** [comment]
Done. Seems to be OK. No more error messages.
